apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding-test-queue-exchange
spec:
  source: test # an existing exchange
  destination: test-queue # an existing queue
  destinationType: queue # can be 'queue' or 'exchange'
  rabbitmqClusterReference:
    name: rabbitmq-main
    namespace: rabbitmq-instance-main
