apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: user-topics
spec:
  tags:
    - policymaker
    - administrator
  rabbitmqClusterReference:
    name: hello-world
  importCredentialsSecret:
      name: user-topics-secret # name of the secret
      namespace: rabbitmq-instance-main
