apiVersion: rabbitmq.com/v1beta1
kind: TopicPermission
metadata:
  name: user-topic-permission
spec:
  vhost: "/" # name of a vhost; required
  user: "test-user"
  permissions:
    exchange: "topic-exchange"
    write: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: hello-world
    namespace: rabbitmq-instance-main
