apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rabbitmq-cluster-configuration
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - list:
        elements:
          - url: https://kubernetes.default.svc
            env: main
            branch: main
  template:
    metadata:
      name: "rabbitmq-configuration-{{env}}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/gattma/rabbitmq-poc-gitops.git
        targetRevision: "{{ branch }}"
        path: cluster-configuration/env/{{ env }}
      destination:
        server: "{{url}}"
        namespace: "rabbitmq-instance-{{ env }}"
